#!/usr/bin/env ruby
# encoding: UTF-8
include ActionDispatch::TestProcess
require 'csv'

puts 'Iniciando script ranking'

filebasepath = '/tmp/'

dialoga = Community['dialoga']
root_report_folder = dialoga.folders.where(:slug => 'relatorios').first
root_report_folder ||= Folder.create!(:profile => dialoga, :name => 'Relatorios')

report_folder = Folder.find_by_slug(DateTime.now.strftime('%Y-%m-%d'))

report_folder ||= Folder.create!(:profile => dialoga, :name => DateTime.now.strftime('%Y-%m-%d'), :parent => root_report_folder)

discussion = ProposalsDiscussionPlugin::Discussion.first

articles = discussion.topics
articles.each do |article|
  puts "#{article.slug}"
  ranking = article.ranking
  filepath = filebasepath + DateTime.now.strftime('%Y-%m-%d-%H-%m-%S') + '-' + "ranking_#{article.slug}.csv"
  CSV.open(filepath, 'w' ) do |csv|
    csv << ['Posição', 'Id', 'Proposta', 'Positivo', 'Negativo', 'Exibições', 'Valor']
    ranking.each_with_index {|r, i| csv << [i+1, r.values].flatten}
  end
  uploaded_file = UploadedFile.new(:uploaded_data => fixture_file_upload(filepath, 'text/csv'), :profile => dialoga, :parent => report_folder)
  uploaded_file.save
end
